<?php 
function my_module_theme($existing, $type, $theme, $path) {
  return array(
    'my_module_email_template_wrapper' => array(
      'variables' => array(
        'user_name' => NULL,
        'content' => NULL,
      ),
      'template' => 'email-wrapper-template',
      'path' => drupal_get_path('module', 'my_module') . '/templates',
    ),
    'my_module_email_template_content' => array(
      'variables' => array(
        'title' => NULL,
        'summary' => NULL,
      ),
      'template' => 'email-content-template',
      'path' => drupal_get_path('module', 'my_module') . '/templates',
    ),
  );
}

// Use the themes to render the message
function my_module_render_message($message) {

  // Load the message.
  $message = message_create('newsletter', array('uid' => $node->uid));
  $message_wrapper = entity_metadata_wrapper('message', $message);

  // Wrap the articles in the content template.
  foreach($wrapper_message->field_articles as $article) {

    $variables['article'] = array(
      'title' => $article->title,
      'summary' => $article->summary,
    );

    // Push the content to a wrapper variable.
    $variables['content'][] = theme('my_module_email_template_content', $variables['article']);
  }

  // The user variable
  $account = $wrapper_message->user;
  $user_name = !empty($account->name->value()) ? $account->name->value() : '';
  $variables['user_name'] = $user_name;
  
  return theme('my_module_email_template_wrapper', $variables);
}

// Use the message module to send the email.
function my_module_send_messages($message) {

  $message_wrapper = entity_metadata_wrapper('message', $message);
  $email = $message_wrapper->email->value();
  // Render the message body.
  $message->arguments['!body'] = my_module_render_message($message);

  // Send the message
  $success = message_notify_send_message($message, array('mail' => $email));
}

// My message view.
function my_module_menu() {
  $items['my-message-view/%'] = array(
    'title' => 'My message view',
    'page callback' => 'my_module_render_message',
    'access arguments' => array('access content'),
    'page arguments' => array(1),
  );

  return $items;
}
